---
- hosts: localhost
  become: true
  vars:
    NODEJS_VERSION: 8
    domain: "localhost"

  tasks:
  - name: Add gpg key for node
    apt_key:
      url:  "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
  - name: Add repo nodejs LTS
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
      state: present
      update_cache: yes
  - name: Install nodejs
    apt:
      name: nodejs
      state: present
  - name: Clone project repository from github
    git:
      repo: "https://github.com/kensanni/More-recipes.git"
      dest: "/home/ubuntu/More-recipes"
      clone: yes
      version: chore/automate-with-ansible-and-packer
  - name: Install nginx
    apt:
      name: nginx
      state:  present
      update_cache: yes
  - name: Set project environment variables
    shell:
      cmd: |
        cat > /home/ubuntu/More-recipes/.env <<EOF
        DATABASE_NAME=more-recipes
        DATABASE_USERNAME=postgres
        DATABASE_PASSWORD=keniks
        DATABASE_NAME_TEST=more-recipes-test
        DATABASE_USERNAME_TEST=postgres
        DATABASE_PASSWORD_TEST=keniks
        JWT_SECRET=kennykay
        REQUEST=https://api.cloudinary.com/v1_1/sannikay/upload
        CLOUD_PRESET=if4gv9sy
        DATABASE_URL=postgres://super_user:awsdevops@ec2-54-186-217-214.us-west-2.compute.amazonaws.com:5432/morerecipe
        EOF
  - name: Remove nginx default configuration
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  - name: enable reverse proxy
    shell:
      cmd: |
        cat > /etc/nginx/sites-available/moreRecipes <<EOF
        server {
          listen 80;
          server_name {{ domain }};
          location / {
            proxy_pass 'http://127.0.0.1:8000';
          }
        }
        EOF
  - name: create symlinks for nginx configuration
    file:
      src:  /etc/nginx/sites-available/moreRecipes
      dest: /etc/nginx/sites-enabled/moreRecipes
      state: link
    notify:
    - restart nginx
  - name: Install necessary dependencies
    shell:  |
      export NODE_ENV=production
      cd /home/ubuntu/More-recipes
      npm install --unsafe-perm
      npm install -g sequelize-cli
      npm install -g babel-cli
      npm install -g pm2
      npm run server:build
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
